export enum ENTITY_TYPES {
  NONE = 'NONE',
  OTHER = 'OTHER',
  GROUP = 'GROUP',
  USER = 'USER',
  GROUP_OF_NAMES = 'GROUP_OF_NAMES',
  ORGANIZATIONAL_UNIT = 'ORGANIZATIONAL_UNIT',
}

export enum DATA_TYPES {
  NONE = 0,
  LIST,
  SINGLE,
  UNIQUE,
}
